import type { TileDef } from "@/engine/types";

export const TILE = 16;
/** Rendered scale. 16px tiles at 2x give the 32px DS-era tile size. */
export const SCALE = 4;
/** Columns in public/assets/tileset.png. */
export const SHEET_COLS = 37;

/**
 * Indices into the sheet. Everything below 1036 is Kenney's Roguelike Modern
 * City; 1036 and up is generated by scripts/build_assets.py.
 */
const T = {
  pavement: 703,
  pavementTan: 744,
  road: 713,
  roadLine: 716,
  crosswalk: 826,
  manhole: 897,
  grass: 888,
  glass: 271,
  glassTall: 272,
  brickPlain: 185,
  brickWindow: 222,
  tanPlain: 193,
  tanWindow: 267,
  roofGrey: 8,
  umbrellaGreen: 552,
  umbrellaOrange: 553,
  doorBrownTop: 982, doorBrownFoot: 1019,
  doorGreenTop: 985, doorGreenFoot: 1022,
  doorOrangeTop: 988, doorOrangeFoot: 1025,
  doorGreyTop: 991, doorGreyFoot: 1028,
  acUnit: 481,
  laundry: 486,
  trafficLight: 518,
  hydrant: 533,
  vending: 592,
  fence: 644,
  stallFruit: 676,
  stallGreens: 677,
  water: 1036,
  waterAlt: 1037,
  foamN: 1038,
  foamE: 1039,
  foamS: 1040,
  foamW: 1041,
  neonRed: 1043,
  neonCyan: 1045,
  neonGold: 1047,
} as const;

export const WATER_TILES = new Set<number>([T.water, T.waterAlt]);
const ROAD_TILES = new Set<number>([T.road, T.roadLine, T.crosswalk, T.manhole]);

/** Palette for the minimap, which reads categories rather than tiles. */
export const MINIMAP = {
  water: "#2f5f86",
  road: "#4a4d52",
  building: "#9aa2a8",
  grass: "#5c8f63",
  ground: "#d2d8d1",
  landmark: "#d94f3d",
  player: "#f8f4e6",
} as const;

export function minimapColor(ground: number, solid: boolean): string {
  if (WATER_TILES.has(ground)) return MINIMAP.water;
  if (solid) return MINIMAP.building;
  if (ROAD_TILES.has(ground)) return MINIMAP.road;
  if (ground === T.grass) return MINIMAP.grass;
  return MINIMAP.ground;
}
export const FOAM = { N: T.foamN, E: T.foamE, S: T.foamS, W: T.foamW };

const walk = (ground: number): TileDef => ({ ground });
const block = (ground: number): TileDef => ({ ground, solid: true });
const prop = (overlay: number, ground = T.pavement): TileDef => ({
  ground,
  overlay,
  solid: true,
});

export const LEGEND: Record<string, TileDef> = {
  ".": walk(T.pavement),
  ",": walk(T.pavementTan),
  r: walk(T.road),
  "=": walk(T.roadLine),
  z: walk(T.crosswalk),
  m: walk(T.manhole),
  g: walk(T.grass),
  "~": walk(T.water),
  w: walk(T.waterAlt),

  K: block(T.brickPlain),
  W: block(T.brickWindow),
  N: block(T.tanPlain),
  M: block(T.tanWindow),
  B: block(T.glass),
  b: block(T.glassTall),
  G: block(T.roofGrey),
  a: { ground: T.brickPlain, overlay: T.acUnit, solid: true },
  L: { ground: T.brickPlain, overlay: T.laundry, solid: true },

  l: prop(T.trafficLight),
  h: prop(T.hydrant),
  v: prop(T.vending),
  f: prop(T.fence),
  u: prop(T.umbrellaOrange),
  U: prop(T.umbrellaGreen),

  "@": walk(T.pavement),

  // Upper halves of the landmark doors. The lower half is the landmark itself.
  p: block(T.doorBrownTop),
  q: block(T.doorGreenTop),
  x: block(T.doorOrangeTop),
  y: block(T.doorGreyTop),

  // Landmark plots are covered by a sprite from landmarks.png, so the tile
  // underneath is plain pavement -- only its solidity matters.
  X: block(T.pavement),
  "1": block(T.pavement),
  "2": block(T.pavement),
  "3": block(T.pavement),
  "4": block(T.pavement),
  "5": block(T.pavement),
};

export const LANDMARKS: Record<string, string> = {
  "1": "experience",
  "2": "education",
  "3": "projects",
  "4": "about",
  "5": "notes",
};

export const SPAWN_CHAR = "@";
