import type { TileDef } from "@/engine/types";

export const TILE = 16;
/** Rendered scale. 16px tiles at 2x give the 32px DS-era tile size. */
export const SCALE = 2;
/** Columns in public/assets/tileset.png. */
export const SHEET_COLS = 37;

/**
 * Indices into the sheet. Everything below 1036 is Kenney's Roguelike Modern
 * City; 1036 and up is generated by scripts/build_assets.py.
 */
const T = {
  pavement: 703,
  pavementTan: 706,
  road: 713,
  roadLine: 716,
  crosswalk: 826,
  manhole: 897,
  grass: 888,
  glass: 271,
  glassTall: 272,
  brick: 222,
  brickAlt: 223,
  tan: 267,
  roofGrey: 8,
  awningGreen: 161,
  awningTeal: 198,
  acUnit: 481,
  laundry: 486,
  trafficLight: 518,
  hydrant: 533,
  vending: 592,
  fence: 644,
  stallFruit: 676,
  stallGreens: 677,
  water: 1036,
  waterAlt: 1037,
  foamN: 1038,
  foamE: 1039,
  foamS: 1040,
  foamW: 1041,
  neonRed: 1043,
  neonCyan: 1045,
  neonGold: 1047,
} as const;

export const WATER_TILES = new Set<number>([T.water, T.waterAlt]);
export const FOAM = { N: T.foamN, E: T.foamE, S: T.foamS, W: T.foamW };

const walk = (ground: number): TileDef => ({ ground });
const block = (ground: number): TileDef => ({ ground, solid: true });
const prop = (overlay: number, ground = T.pavement): TileDef => ({
  ground,
  overlay,
  solid: true,
});

export const LEGEND: Record<string, TileDef> = {
  ".": walk(T.pavement),
  ",": walk(T.pavementTan),
  r: walk(T.road),
  "=": walk(T.roadLine),
  z: walk(T.crosswalk),
  m: walk(T.manhole),
  g: walk(T.grass),
  "~": walk(T.water),
  w: walk(T.waterAlt),

  K: block(T.brick),
  a: { ground: T.brick, overlay: T.acUnit, solid: true },
  L: { ground: T.brickAlt, overlay: T.laundry, solid: true },
  N: block(T.tan),
  B: block(T.glass),
  b: block(T.glassTall),
  G: block(T.roofGrey),

  l: prop(T.trafficLight),
  h: prop(T.hydrant),
  v: prop(T.vending),
  f: prop(T.fence),
  s: prop(T.stallFruit),
  S: prop(T.stallGreens),

  "@": walk(T.pavement),

  "1": { ground: T.awningTeal, overlay: T.neonRed, solid: true },
  "2": { ground: T.awningGreen, overlay: T.neonCyan, solid: true },
  "3": { ground: T.awningTeal, overlay: T.neonGold, solid: true },
  "4": { ground: T.awningGreen, overlay: T.neonRed, solid: true },
  "5": { ground: T.awningTeal, overlay: T.neonCyan, solid: true },
};

export const LANDMARKS: Record<string, string> = {
  "1": "experience",
  "2": "education",
  "3": "projects",
  "4": "about",
  "5": "notes",
};

export const SPAWN_CHAR = "@";
